/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCampaignThemesRouteImport } from './routes/dashboard.campaign-themes'
import { Route as DashboardCompetitiveContextRouteImport } from './routes/dashboard.competitive-context'
import { Route as DashboardCreativeFormatsRouteImport } from './routes/dashboard.creative-formats'
import { Route as DashboardFutureFocusRouteImport } from './routes/dashboard.future-focus'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardPlatformsRouteImport } from './routes/dashboard.platforms'
import { Route as DashboardPositioningMessagingRouteImport } from './routes/dashboard.positioning-messaging'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignThemesRoute = DashboardCampaignThemesRouteImport.update({
  id: '/campaign-themes',
  path: '/campaign-themes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitiveContextRoute =
  DashboardCompetitiveContextRouteImport.update({
    id: '/competitive-context',
    path: '/competitive-context',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCreativeFormatsRoute =
  DashboardCreativeFormatsRouteImport.update({
    id: '/creative-formats',
    path: '/creative-formats',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFutureFocusRoute = DashboardFutureFocusRouteImport.update({
  id: '/future-focus',
  path: '/future-focus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformsRoute = DashboardPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPositioningMessagingRoute =
  DashboardPositioningMessagingRouteImport.update({
    id: '/positioning-messaging',
    path: '/positioning-messaging',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/dashboard/campaign-themes': typeof DashboardCampaignThemesRoute
  '/dashboard/competitive-context': typeof DashboardCompetitiveContextRoute
  '/dashboard/creative-formats': typeof DashboardCreativeFormatsRoute
  '/dashboard/future-focus': typeof DashboardFutureFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/platforms': typeof DashboardPlatformsRoute
  '/dashboard/positioning-messaging': typeof DashboardPositioningMessagingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/dashboard/campaign-themes': typeof DashboardCampaignThemesRoute
  '/dashboard/competitive-context': typeof DashboardCompetitiveContextRoute
  '/dashboard/creative-formats': typeof DashboardCreativeFormatsRoute
  '/dashboard/future-focus': typeof DashboardFutureFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/platforms': typeof DashboardPlatformsRoute
  '/dashboard/positioning-messaging': typeof DashboardPositioningMessagingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/dashboard/campaign-themes': typeof DashboardCampaignThemesRoute
  '/dashboard/competitive-context': typeof DashboardCompetitiveContextRoute
  '/dashboard/creative-formats': typeof DashboardCreativeFormatsRoute
  '/dashboard/future-focus': typeof DashboardFutureFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/platforms': typeof DashboardPlatformsRoute
  '/dashboard/positioning-messaging': typeof DashboardPositioningMessagingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/dashboard/campaign-themes'
    | '/dashboard/competitive-context'
    | '/dashboard/creative-formats'
    | '/dashboard/future-focus'
    | '/dashboard/overview'
    | '/dashboard/platforms'
    | '/dashboard/positioning-messaging'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/dashboard/campaign-themes'
    | '/dashboard/competitive-context'
    | '/dashboard/creative-formats'
    | '/dashboard/future-focus'
    | '/dashboard/overview'
    | '/dashboard/platforms'
    | '/dashboard/positioning-messaging'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/dashboard/campaign-themes'
    | '/dashboard/competitive-context'
    | '/dashboard/creative-formats'
    | '/dashboard/future-focus'
    | '/dashboard/overview'
    | '/dashboard/platforms'
    | '/dashboard/positioning-messaging'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaign-themes': {
      id: '/dashboard/campaign-themes'
      path: '/campaign-themes'
      fullPath: '/dashboard/campaign-themes'
      preLoaderRoute: typeof DashboardCampaignThemesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitive-context': {
      id: '/dashboard/competitive-context'
      path: '/competitive-context'
      fullPath: '/dashboard/competitive-context'
      preLoaderRoute: typeof DashboardCompetitiveContextRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creative-formats': {
      id: '/dashboard/creative-formats'
      path: '/creative-formats'
      fullPath: '/dashboard/creative-formats'
      preLoaderRoute: typeof DashboardCreativeFormatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/future-focus': {
      id: '/dashboard/future-focus'
      path: '/future-focus'
      fullPath: '/dashboard/future-focus'
      preLoaderRoute: typeof DashboardFutureFocusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/platforms': {
      id: '/dashboard/platforms'
      path: '/platforms'
      fullPath: '/dashboard/platforms'
      preLoaderRoute: typeof DashboardPlatformsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/positioning-messaging': {
      id: '/dashboard/positioning-messaging'
      path: '/positioning-messaging'
      fullPath: '/dashboard/positioning-messaging'
      preLoaderRoute: typeof DashboardPositioningMessagingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCampaignThemesRoute: typeof DashboardCampaignThemesRoute
  DashboardCompetitiveContextRoute: typeof DashboardCompetitiveContextRoute
  DashboardCreativeFormatsRoute: typeof DashboardCreativeFormatsRoute
  DashboardFutureFocusRoute: typeof DashboardFutureFocusRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardPlatformsRoute: typeof DashboardPlatformsRoute
  DashboardPositioningMessagingRoute: typeof DashboardPositioningMessagingRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignThemesRoute: DashboardCampaignThemesRoute,
  DashboardCompetitiveContextRoute: DashboardCompetitiveContextRoute,
  DashboardCreativeFormatsRoute: DashboardCreativeFormatsRoute,
  DashboardFutureFocusRoute: DashboardFutureFocusRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardPlatformsRoute: DashboardPlatformsRoute,
  DashboardPositioningMessagingRoute: DashboardPositioningMessagingRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
